version : "3.8"
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - ezlearner-network  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
      - ezlearner-network
    depends_on:
      - prometheus
  jobmanager:
    image: ${FLINK_DOCKER_IMAGE_NAME:-flink}
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - ezlearner-network
  taskmanager:
    image: ${FLINK_DOCKER_IMAGE_NAME:-flink}
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    links:
      - "jobmanager:jobmanager"
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - ezlearner-network
  zookeeper:
    image: priyam569/zookeeper
    expose:
      - "2181"
    command: sh -c "./apache-zookeeper-3.8.1-bin/bin zkServer.sh start-foreground"
    networks:
      - ezlearner-network
  kafka:
    image: wurstmeister/kafka:2.12-2.3.0 #wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      #KAFKA_CREATE_TOPICS: "person:1:1"
    depends_on:
      - zookeeper
    command: sh -c "start-kafka.sh"
    networks:
      - ezlearner-network
  serviceconsumer:
    image: priyam569/servicesconsumer
    ports:
      - "8087:8085"
    depends_on: 
      - kafka
    networks:
      - ezlearner-network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 55s
        max_attempts: 3
        window: 180s
  SERVICES:
    image: priyam569/services:latest
    mem_limit: 700m
    ports:
      - "8082:8082"
    networks:
      - ezlearner-network
    depends_on: 
      - kafka
    deploy:
      restart_policy:
        condition: on-failure
        delay: 55s
        max_attempts: 3
        window: 120s
    environment:
       SERVER.PORT: 8082	 
       SPRING_PROFILES_ACTIVE: default
  #flinkproduceraggregator:
   # image: priyam569/flinkproduceraggregator
     #ports:
       #- "8088:8080"
     #networks:
       #- ezlearner-network
     #depends_on:
       #- taskmanager
       #- kafka
     #deploy:
       #restart_policy:
         #condition: on-failure
         #delay: 55s
         #max_attempts: 3
         #window: 180s
networks:
  ezlearner-network:
volumes:
  db:
    driver: local
