version : "3.8"
services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    command: sh -c "chmod -R 755 /data && zkServer.sh start-foreground"
    volumes:
      - zookeeper-logs:/var/lib/zookeeper/logs
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER.REQUEST.TIMEOUT: 30000

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HOME: /opt/kafka_2.13-2.8.0
      #KAFKA_ADVERTISED_HOST_NAME: localhost
      #KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      #KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      #KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      #KAFKA_HOME: "/opt/kafka_2.13-2.8.1/bin"
    #command: sh -c "/opt/kafka_2.13-2.8.1/bin/kafka-server-start.sh /opt/kafka_2.13-2.8.1/config/server.properties"
volumes:
  zookeeper-logs:





  #zookeeper:
   # image: priyam569/zookeeper
   # expose:
   #   - "2181"
   # command: sh -c "/apache-zookeeper-3.8.1-bin/bin zkServer.sh"
    #environment:
     # - ZOO_ENABLE_AUTH=yes
      #- ZOO_SERVER_USERS=user1,user2
      #- ZOO_SERVER_PASSWORDS=pass4user1,pass4user2
      #- ZOO_CLIENT_USER=user1
      #- ZOO_CLIENT_PASSWORD=pass4user1
    #build: .
    #user: newuser


